### ISSUE TITLE
已经不能用了

### ISSUE THREAD

**Issue by lengyanwl** [lyz1810/edge-tts#3]
报错信息：
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=8203ebc7d47c49e1a37bbced96793ddc'

**Comment by lyz1810** [comment]
拉去最新代码
